//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuneBoss_V2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>/9j/4AAQSkZJRgABAQEAAAAAAAD/4QB2RXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAA" +
            "AAAZKGAAcAAABCAAAALAAAAABVTklDT0RFAABDAG8AbQBwAHIAZQBzAHMAZQBkACAAYgB5ACAAagBwAG" +
            "UAZwAtAHIAZQBjAG8AbQBwAHIAZQBzAHP/2wBDAAQEBAQEBAQEBAQGBgUGBggHBwcHCAwJCQkJCQwTDA" +
            "4MDA4MExEUEA8QFBEeFxUVFx4iHRsdIiolJSo0MjRERFz/2wBDAQQEBAQEBAQEBAQGBgUGBggHBwcHCA" +
            "wJCQkJCQwTDA4MDA4MExEUEA8QFBEeFxUVFx4iHRsdIiolJSo0MjRERFz/wgARCAAkACQDASIAAhEBAx" +
            "EB/8QAGwAAAgIDAQAAAAAAAAAAAAAABQcBBgACAwn/2gAIAQEAAAAAX9X6w11JAQsDsYie4u2YJI1p9o" +
            "SNvSn/xAAYAQEAAwEAAAAAAAAAAAAAAAADAAEEAv/aAAgBAhAAAAAIS3mTjb//xAAXAQADAQAAAAAAAA" +
            "AAAAAAAAABAgME/9oACAEDEAAAAHFojQrZf//EADMQAAEDAwIDBQQLAAAAAAAAAAECAwQAERIFBhMhMQ" +
            "cIFEFhMlGBsSIzQkNEcYKRocHS/9oACAEBAAE/AN4bv1jtA1ZG4dfbiOT3YsVpttuMhEePHSkrDbYWXF" +
            "G6lkkqNIaZJsqDG5iybMN3PuPs0I8fh5qhxSLG1o7ZKiPhTbUYHN2DEsFAYcFsfzjUDvF7+2PpOjbagx" +
            "tGnRIUNDUd6ZFd44ZbJQhCyy8hJwSkCmkK4MJaeoiMcrX6tpFSpUaC2o2C3CMEIBupR9w/s0V6jFjiCX" +
            "0qkOX4aWzdxORurI9LetRXzKaVxUNoXcMqQlVwCkczfp863ER4iFjewigc/RxYrn4COGAeP4JnEnyXwu" +
            "Vr8qW3NYbVqLsUuTHF4445BtCgbY4k1mmChSzd7U5PmRYi/obYpFQ9PW0tchTylurBU79KyFKV6DrW4r" +
            "CRCCegigfs4uo+TcOE4rLHwzBQADbLhpFK9rEi6yL8jz58qiQEQC7m6FrItmU4qAT9kXJo/VHmQfI2sk" +
            "VuVJRKiJUnEiN0sR94vyNd42DpOyd/xoO2tFhQoc7RYs16MygtsB8OvMlaEIISi6UC9qO5ZR/CRfgHB8" +
            "l0NxyQbiFFv+Tn+6TuaWg5Jhxb3B6OdR+quzfs37P3+z/ZUyZsrRZcqXosKZIkTITUl91+S0HnFrceCl" +
            "G6lV//xAAcEQEAAwACAwAAAAAAAAAAAAABAAIRAyExMlH/2gAIAQIBAT8AAzWZV6yPJccLQ9SBLeWcnV" +
            "3Jr9gGHU//xAAbEQEAAwADAQAAAAAAAAAAAAABAAIRECFRMf/aAAgBAwEBPwBXcJtvYUqg5LdLwfCUBD" +
            "Zh5Fdn/9k=</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Inventory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Inventory"]));
            }
            set {
                this["Inventory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>/9j/4AAQSkZJRgABAQEAAAAAAAD/4QB2RXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAA" +
            "AAAZKGAAcAAABCAAAALAAAAABVTklDT0RFAABDAG8AbQBwAHIAZQBzAHMAZQBkACAAYgB5ACAAagBwAG" +
            "UAZwAtAHIAZQBjAG8AbQBwAHIAZQBzAHP/2wBDAAQEBAQEBAQEBAQGBgUGBggHBwcHCAwJCQkJCQwTDA" +
            "4MDA4MExEUEA8QFBEeFxUVFx4iHRsdIiolJSo0MjRERFz/2wBDAQQEBAQEBAQEBAQGBgUGBggHBwcHCA" +
            "wJCQkJCQwTDA4MDA4MExEUEA8QFBEeFxUVFx4iHRsdIiolJSo0MjRERFz/wgARCAAkACQDASIAAhEBAx" +
            "EB/8QAGwAAAgIDAQAAAAAAAAAAAAAABQcBBgACAwn/2gAIAQEAAAAAX9X6w11JAQsDsYie4u2YJI1p9o" +
            "SNvSn/xAAYAQEAAwEAAAAAAAAAAAAAAAADAAEEAv/aAAgBAhAAAAAIS3mTjb//xAAXAQADAQAAAAAAAA" +
            "AAAAAAAAABAgME/9oACAEDEAAAAHFojQrZf//EADMQAAEDAwIDBQQLAAAAAAAAAAECAwQAERIFBhMhMQ" +
            "cIFEFhMlGBsSIzQkNEcYKRocHS/9oACAEBAAE/AN4bv1jtA1ZG4dfbiOT3YsVpttuMhEePHSkrDbYWXF" +
            "G6lkkqNIaZJsqDG5iybMN3PuPs0I8fh5qhxSLG1o7ZKiPhTbUYHN2DEsFAYcFsfzjUDvF7+2PpOjbagx" +
            "tGnRIUNDUd6ZFd44ZbJQhCyy8hJwSkCmkK4MJaeoiMcrX6tpFSpUaC2o2C3CMEIBupR9w/s0V6jFjiCX" +
            "0qkOX4aWzdxORurI9LetRXzKaVxUNoXcMqQlVwCkczfp863ER4iFjewigc/RxYrn4COGAeP4JnEnyXwu" +
            "Vr8qW3NYbVqLsUuTHF4445BtCgbY4k1mmChSzd7U5PmRYi/obYpFQ9PW0tchTylurBU79KyFKV6DrW4r" +
            "CRCCegigfs4uo+TcOE4rLHwzBQADbLhpFK9rEi6yL8jz58qiQEQC7m6FrItmU4qAT9kXJo/VHmQfI2sk" +
            "VuVJRKiJUnEiN0sR94vyNd42DpOyd/xoO2tFhQoc7RYs16MygtsB8OvMlaEIISi6UC9qO5ZR/CRfgHB8" +
            "l0NxyQbiFFv+Tn+6TuaWg5Jhxb3B6OdR+quzfs37P3+z/ZUyZsrRZcqXosKZIkTITUl91+S0HnFrceCl" +
            "G6lV//xAAcEQEAAwACAwAAAAAAAAAAAAABAAIRAyExMlH/2gAIAQIBAT8AAzWZV6yPJccLQ9SBLeWcnV" +
            "3Jr9gGHU//xAAbEQEAAwADAQAAAAAAAAAAAAABAAIRECFRMf/aAAgBAwEBPwBXcJtvYUqg5LdLwfCUBD" +
            "Zh5Fdn/9k=</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Gear {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Gear"]));
            }
            set {
                this["Gear"] = value;
            }
        }
    }
}
